#!/bin/bash
#

# Generated by CHARMM-GUI (http://www.charmm-gui.org) v3.7

# This folder contains GROMACS formatted force fields, a pre-optimized PDB structure, and GROMACS inputs.
# All input files were optimized for GROMACS 2019.2 or above, so lower version of GROMACS can cause some errors.
# We adopted the Verlet cut-off scheme for all minimization, equilibration, and production steps because it is 
# faster and more accurate than the group scheme. If you have a trouble with a performance of Verlet scheme while 
# running parallelized simulation, you should check if you are using appropriate command line.
# For MPI parallelizing, we recommand following command:
# mpirun -np $NUM_CPU gmx mdrun -ntomp 1

init="step5_input"
rest_prefix="step5_input"
mini_prefix="step6.0_minimization"
equi_prefix="step6.%d_equilibration"
prod_prefix="step7_production"
prod_step="step7"


# Minimization
# In the case that there is a problem during minimization using a single precision of GROMACS, please try to use 
# a double precision of GROMACS only for the minimization step.
gmx grompp -f "${mini_prefix}.mdp" -o "${mini_prefix}.tpr" -c "${init}.gro" -r "${rest_prefix}.gro" -p topol.top -n index.ndx
gmx mdrun -v -deffnm "${mini_prefix}"

printf "0\n" | gmx editconf -f step6.0_minimization.gro -o 4zw9_full_atom_minim.pdb -n index

# # Equilibration
# cnt=1
# cntmax=6

# while [ $cnt -le $cntmax ]
# do
#     pcnt=$((cnt-1))
#     istep=$(printf "${equi_prefix}" $cnt)
#     pstep=$(printf "${equi_prefix}" $pcnt)
#     if [ $cnt -eq 1 ]; then
#         pstep=$mini_prefix
#     fi

#     gmx grompp -f "${istep}.mdp" -o "${istep}.tpr" -c "${pstep}.gro" -r "${rest_prefix}.gro" -p topol.top -n index.ndx
#     gmx mdrun -v -deffnm "${istep}"
#     cnt=$((cnt+1))
# done

# # Production
# cnt=1
# cntmax=10

# while [ $cnt -le $cntmax ]
# do
#     pcnt=$((cnt-1))
#     istep="${prod_step}_${cnt}"
#     pstep="${prod_step}_${pcnt}"

#     if [ $cnt -eq 1 ]; then
#         pstep=$(printf "${equi_prefix}" 6)
#         gmx grompp -f "${prod_prefix}.mdp" -o "${istep}.tpr" -c "${pstep}.gro" -p topol.top -n index.ndx
#     else
#         gmx grompp -f "${prod_prefix}.mdp" -o "${istep}.tpr" -c "${pstep}.gro" -t "${pstep}.cpt" -p topol.top -n index.ndx
#     fi

#     gmx mdrun -v -deffnm "${istep}"
#     cnt=$((cnt+1))
# done

